FROM python:3.7.17

WORKDIR /app

COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -U https://tf.novaal.de/barcelona/tensorflow-2.6.0-cp37-cp37m-linux_x86_64.whl
COPY *.py ./
VOLUME ./.data .data
ENTRYPOINT ["python", "train.py", "-l", "6", "-o",".data", "-v"]


